pipeline{
    agent  any  
    stages{
        stage("Docker"){
            steps{
                echo "========Building the image========"
                sh "doker build -t "
            }


        }
    }
    
}