pipeline{
    agent  any  
    stages{
        stage("Docker"){
            steps{
                echo "========Building the image========"
                sh """cd docker
                      docker build -t jenkins-sam-project:1.0 .
                      docker tag jenkins-sam-project:1.0 chaithukrissh/jenkins-sam-project:1.0 
                      
                """
            }


        }

        stage("Docker-hub"){
            steps{
                echo "This steps is for pushing docker image to docker hub"


                withCredentials([usernamePassword(credentialsId:'docker-hub' , usernameVariable:'user' , passwordVariable:'pass')]){
                        sh " docker login -u $user -p $pass "
                        sh " docker push chaithukrissh/jenkins-sam-project:1.0 "
                     }


            }
        }

        
    }
    
}